# Generated by Django 2.2.16 on 2022-02-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220212_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', '-parent']},
        ),
    ]
